name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
           docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
           docker build -t spring-cicd .
           docker tag spring-cicd imeahmik@gmail.com/ordoapi:${GITHUB_SHA::7}
           docker push imeahmik@gmail.com/ordoapi:${GITHUB_SHA::7}
           
    - name: Deploy
      uses: actions/checkout@v3
      with:
          host: http://222.108.21.14
          username: ordo
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: 
            docker pull imeahmik@gmail.com/ordoapi:${GITHUB_SHA::7}
            docker tag imeahmik@gmail.com/ordoapi:${GITHUB_SHA::7} ordoapi
            docker stop server
            docker run -d --rm --name server -p 80:8080 spring-cicd
